[package]

name = "piston2d-sprite"
version = "0.0.1"
authors = ["Coeuvre Wong <coeuvre@gmail.com>"]
keywords = ["sprite", "animation", "2d"]
description = "A library for sprite hierarchy and scene management"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/sprite.git"
homepage = "https://github.com/pistondevelopers/sprite"

[lib]

name = "sprite"
path = "./src/lib.rs"

[dependencies.pistoncore-event]

git = "https://github.com/pistondevelopers/event"

[dependencies.quack]

git = "https://github.com/pistondevelopers/quack"

[dependencies.piston2d-graphics]

git = "https://github.com/pistondevelopers/graphics"

[dependencies.piston-ai_behavior]

git = "https://github.com/pistondevelopers/ai_behavior"

[dependencies.uuid]

git = "https://github.com/rust-lang/uuid"

