[package]

name = "sprite"
version = "0.0.0"
authors = ["Coeuvre Wong <coeuvre@gmail.com>"]

[lib]

name = "sprite"
path = "./src/lib.rs"

[dependencies.uuid]

git = "https://github.com/rust-lang/uuid"

[dependencies.event]

git = "https://github.com/PistonDevelopers/rust-event"

[dependencies.graphics]

git = "https://github.com/pistondevelopers/rust-graphics"

