[package]

name = "sprite"
version = "0.0.0"
authors = ["Coeuvre Wong <coeuvre@gmail.com>"]

[lib]

name = "sprite"
path = "./src/lib.rs"

[dependencies.uuid]

git = "https://github.com/rust-lang/uuid"

[dependencies.ai_behavior]

git = "https://github.com/pistondevelopers/ai_behavior"

[dependencies.event]

git = "https://github.com/pistondevelopers/event"

[dependencies.graphics]

git = "https://github.com/pistondevelopers/graphics"

[dependencies.current]

git = "https://github.com/pistondevelopers/current"

